language: bash

env:
  matrix:
  - KUBECTL_VERSION=v1.21.2 NODE_VERSION=v1.21.2
  - KUBECTL_VERSION=v1.20.8 NODE_VERSION=v1.20.8
  - KUBECTL_VERSION=v1.19.12 NODE_VERSION=v1.19.12
  - KUBECTL_VERSION=v1.18.20 NODE_VERSION=v1.18.20
  - KUBECTL_VERSION=v1.17.17 NODE_VERSION=v1.17.17
  global:
  - KIND_VERSION=v0.11.1

services:
- docker

before_script:
# Download and install kubectl
- curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
# Download and install kind
- curl -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/${KIND_VERSION}/kind-linux-amd64 && chmod +x kind && sudo mv kind /usr/local/bin/
# Create a new kubernetes cluster
- kind create cluster --image="kindest/node:${NODE_VERSION}"
# Show version
- kubectl version

script:
- make test

matrix:
  include:
  - &bash
    language: bash
    go: null
    env: null
    before_script: null
    script:
    - ./scripts/verify-authors.sh
  - <<: *bash
    script:
    - make lint
  - <<: *bash
    script:
    - make image
