language: bash

env:
  matrix:
  - KUBECTL_VERSION=v1.28.1 NODE_VERSION=v1.28.1
  - KUBECTL_VERSION=v1.27.5 NODE_VERSION=v1.27.5
  - KUBECTL_VERSION=v1.26.8 NODE_VERSION=v1.26.8
  - KUBECTL_VERSION=v1.25.13 NODE_VERSION=v1.25.13
  - KUBECTL_VERSION=v1.24.17 NODE_VERSION=v1.24.17
  - KUBECTL_VERSION=v1.23.2 NODE_VERSION=v1.23.2
  - KUBECTL_VERSION=v1.22.5 NODE_VERSION=v1.22.5
  - KUBECTL_VERSION=v1.21.8 NODE_VERSION=v1.21.8
  - KUBECTL_VERSION=v1.20.14 NODE_VERSION=v1.20.14
  global:
  - KIND_VERSION=v0.11.1

services:
- docker

before_script:
# Download and install kubectl
- curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
# Download and install kind
- curl -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/${KIND_VERSION}/kind-linux-amd64 && chmod +x kind && sudo mv kind /usr/local/bin/
# Create a new kubernetes cluster
- kind create cluster --image="kindest/node:${NODE_VERSION}"
# Show version
- kubectl version

script:
- make test

matrix:
  include:
  - &bash
    language: bash
    go: null
    env: null
    before_script: null
    script:
    - ./scripts/verify-authors.sh
  - <<: *bash
    script:
    - make lint
  - <<: *bash
    script:
    - make image
