platform: linux
image_resource:
  type: registry-image
  source:
    repository: alpine
    tag: "3.15"
inputs:
- name: version
outputs:
- name: output
run:
  path: sh
  args:
  - -exuc
  - |
    cat <<EOF > output/build-args-file
    KUBERNETES_VERSION=$(cat version/version)
    EOF
