
# ci/pipeline.yml
#
# DO NOT MAKE CHANGES TO THIS FILE. Instead, modify ci/pipeline.yml.erb and
# execute build-pipeline-yml.
#
# created: 2023-08-24T16:34:13+02:00
#
resource_types:
- name: file-url
  type: registry-image
  source:
    repository: pivotalservices/concourse-curl-resource
    tag: latest

resources:
- name: ubuntu-20.04
  type: registry-image
  source:
    repository: ubuntu
    tag: "20.04"

- name: kubernetes-resource
  type: git
  source:
    uri: https://github.com/cycloidio/kubernetes-resource.git
    branch: master

- name: kubernetes-resource-release
  type: git
  source:
    uri: https://github.com/cycloidio/kubernetes-resource.git
    branch: master
    tag_filter: v*

- name: kubernetes-resource-image-1.20
  type: registry-image
  source:
    repository: cycloid/kubernetes-resource
    tag: "1.20"
    username: ((docker-username))
    password: ((docker-password))

- name: kubernetes-resource-image-1.21
  type: registry-image
  source:
    repository: cycloid/kubernetes-resource
    tag: "1.21"
    username: ((docker-username))
    password: ((docker-password))

- name: kubernetes-resource-image-1.22
  type: registry-image
  source:
    repository: cycloid/kubernetes-resource
    tag: "1.22"
    username: ((docker-username))
    password: ((docker-password))

- name: kubernetes-resource-image-1.23
  type: registry-image
  source:
    repository: cycloid/kubernetes-resource
    tag: "1.23"
    username: ((docker-username))
    password: ((docker-password))

- name: kubernetes-resource-image-1.24
  type: registry-image
  source:
    repository: cycloid/kubernetes-resource
    tag: "1.24"
    username: ((docker-username))
    password: ((docker-password))

- name: kubernetes-resource-image-1.25
  type: registry-image
  source:
    repository: cycloid/kubernetes-resource
    tag: "1.25"
    username: ((docker-username))
    password: ((docker-password))

- name: kubernetes-resource-image-1.26
  type: registry-image
  source:
    repository: cycloid/kubernetes-resource
    tag: "1.26"
    username: ((docker-username))
    password: ((docker-password))

- name: kubernetes-resource-image-1.27
  type: registry-image
  source:
    repository: cycloid/kubernetes-resource
    tag: "1.27"
    username: ((docker-username))
    password: ((docker-password))

- name: kubernetes-resource-image-1.28
  type: registry-image
  source:
    repository: cycloid/kubernetes-resource
    tag: "1.28"
    username: ((docker-username))
    password: ((docker-password))

- name: kubernetes-resource-image-latest
  type: registry-image
  source:
    repository: cycloid/kubernetes-resource
    tag: "latest"
    username: ((docker-username))
    password: ((docker-password))


- name: kubernetes-resource-image-edge
  type: registry-image
  source:
    repository: cycloid/kubernetes-resource
    tag: edge
    username: ((docker-username))
    password: ((docker-password))


- name: stable-1.20
  type: file-url
  source:
    url: https://storage.googleapis.com/kubernetes-release/release/stable-1.20.txt
    filename: version

- name: stable-1.21
  type: file-url
  source:
    url: https://storage.googleapis.com/kubernetes-release/release/stable-1.21.txt
    filename: version

- name: stable-1.22
  type: file-url
  source:
    url: https://storage.googleapis.com/kubernetes-release/release/stable-1.22.txt
    filename: version

- name: stable-1.23
  type: file-url
  source:
    url: https://storage.googleapis.com/kubernetes-release/release/stable-1.23.txt
    filename: version

- name: stable-1.24
  type: file-url
  source:
    url: https://storage.googleapis.com/kubernetes-release/release/stable-1.24.txt
    filename: version

- name: stable-1.25
  type: file-url
  source:
    url: https://storage.googleapis.com/kubernetes-release/release/stable-1.25.txt
    filename: version

- name: stable-1.26
  type: file-url
  source:
    url: https://storage.googleapis.com/kubernetes-release/release/stable-1.26.txt
    filename: version

- name: stable-1.27
  type: file-url
  source:
    url: https://storage.googleapis.com/kubernetes-release/release/stable-1.27.txt
    filename: version

- name: stable-1.28
  type: file-url
  source:
    url: https://storage.googleapis.com/kubernetes-release/release/stable-1.28.txt
    filename: version

- name: latest
  type: file-url
  source:
    url: https://storage.googleapis.com/kubernetes-release/release/latest.txt
    filename: version


jobs:
- name: build-kubernetes-resource-image-edge
  public: true
  serial: true
  plan:
  - do:
    - in_parallel:
      - get: kubernetes-resource
        trigger: true
      - get: ubuntu-20.04
        params:
          format: oci
        trigger: true
      - get: latest
        trigger: true

    - task: build-build-args-file
      file: kubernetes-resource/ci/tasks/build-build-args-file.yml
      input_mapping:
        version: latest

    - task: build
      privileged: true
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: concourse/oci-build-task
            tag: latest
        inputs:
          - name: kubernetes-resource
            path: source
          - name: output
          - name: ubuntu-20.04
        run:
          path: build
        outputs:
          - name: image
        params:
          CONTEXT: source
          BUILD_ARGS_FILE: output/build-args-file
          IMAGE_ARG_base_image: ubuntu-20.04/image.tar

    - put: kubernetes-resource-image-edge
      params:
        image: image/image.tar


- name: build-kubernetes-resource-image-1.20
  public: true
  serial: true
  plan:
  - do:
    - in_parallel:
      - get: kubernetes-resource-release
        trigger: true
      - get: ubuntu-20.04
        params:
          format: oci
        trigger: true
      - get: stable-1.20
        trigger: true

    - task: build-build-args-file
      file: kubernetes-resource-release/ci/tasks/build-build-args-file.yml
      input_mapping:
        version: stable-1.20

    - task: build
      privileged: true
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: concourse/oci-build-task
            tag: latest
        inputs:
          - name: kubernetes-resource-release
            path: source
          - name: output
          - name: ubuntu-20.04
        run:
          path: build
        outputs:
          - name: image
        params:
          CONTEXT: source
          BUILD_ARGS_FILE: output/build-args-file
          IMAGE_ARG_base_image: ubuntu-20.04/image.tar

    - put: kubernetes-resource-image-1.20
      params:
        image: image/image.tar

- name: build-kubernetes-resource-image-1.21
  public: true
  serial: true
  plan:
  - do:
    - in_parallel:
      - get: kubernetes-resource-release
        trigger: true
      - get: ubuntu-20.04
        params:
          format: oci
        trigger: true
      - get: stable-1.21
        trigger: true

    - task: build-build-args-file
      file: kubernetes-resource-release/ci/tasks/build-build-args-file.yml
      input_mapping:
        version: stable-1.21

    - task: build
      privileged: true
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: concourse/oci-build-task
            tag: latest
        inputs:
          - name: kubernetes-resource-release
            path: source
          - name: output
          - name: ubuntu-20.04
        run:
          path: build
        outputs:
          - name: image
        params:
          CONTEXT: source
          BUILD_ARGS_FILE: output/build-args-file
          IMAGE_ARG_base_image: ubuntu-20.04/image.tar

    - put: kubernetes-resource-image-1.21
      params:
        image: image/image.tar

- name: build-kubernetes-resource-image-1.22
  public: true
  serial: true
  plan:
  - do:
    - in_parallel:
      - get: kubernetes-resource-release
        trigger: true
      - get: ubuntu-20.04
        params:
          format: oci
        trigger: true
      - get: stable-1.22
        trigger: true

    - task: build-build-args-file
      file: kubernetes-resource-release/ci/tasks/build-build-args-file.yml
      input_mapping:
        version: stable-1.22

    - task: build
      privileged: true
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: concourse/oci-build-task
            tag: latest
        inputs:
          - name: kubernetes-resource-release
            path: source
          - name: output
          - name: ubuntu-20.04
        run:
          path: build
        outputs:
          - name: image
        params:
          CONTEXT: source
          BUILD_ARGS_FILE: output/build-args-file
          IMAGE_ARG_base_image: ubuntu-20.04/image.tar

    - put: kubernetes-resource-image-1.22
      params:
        image: image/image.tar

- name: build-kubernetes-resource-image-1.23
  public: true
  serial: true
  plan:
  - do:
    - in_parallel:
      - get: kubernetes-resource-release
        trigger: true
      - get: ubuntu-20.04
        params:
          format: oci
        trigger: true
      - get: stable-1.23
        trigger: true

    - task: build-build-args-file
      file: kubernetes-resource-release/ci/tasks/build-build-args-file.yml
      input_mapping:
        version: stable-1.23

    - task: build
      privileged: true
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: concourse/oci-build-task
            tag: latest
        inputs:
          - name: kubernetes-resource-release
            path: source
          - name: output
          - name: ubuntu-20.04
        run:
          path: build
        outputs:
          - name: image
        params:
          CONTEXT: source
          BUILD_ARGS_FILE: output/build-args-file
          IMAGE_ARG_base_image: ubuntu-20.04/image.tar

    - put: kubernetes-resource-image-1.23
      params:
        image: image/image.tar

- name: build-kubernetes-resource-image-1.24
  public: true
  serial: true
  plan:
  - do:
    - in_parallel:
      - get: kubernetes-resource-release
        trigger: true
      - get: ubuntu-20.04
        params:
          format: oci
        trigger: true
      - get: stable-1.24
        trigger: true

    - task: build-build-args-file
      file: kubernetes-resource-release/ci/tasks/build-build-args-file.yml
      input_mapping:
        version: stable-1.24

    - task: build
      privileged: true
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: concourse/oci-build-task
            tag: latest
        inputs:
          - name: kubernetes-resource-release
            path: source
          - name: output
          - name: ubuntu-20.04
        run:
          path: build
        outputs:
          - name: image
        params:
          CONTEXT: source
          BUILD_ARGS_FILE: output/build-args-file
          IMAGE_ARG_base_image: ubuntu-20.04/image.tar

    - put: kubernetes-resource-image-1.24
      params:
        image: image/image.tar

- name: build-kubernetes-resource-image-1.25
  public: true
  serial: true
  plan:
  - do:
    - in_parallel:
      - get: kubernetes-resource-release
        trigger: true
      - get: ubuntu-20.04
        params:
          format: oci
        trigger: true
      - get: stable-1.25
        trigger: true

    - task: build-build-args-file
      file: kubernetes-resource-release/ci/tasks/build-build-args-file.yml
      input_mapping:
        version: stable-1.25

    - task: build
      privileged: true
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: concourse/oci-build-task
            tag: latest
        inputs:
          - name: kubernetes-resource-release
            path: source
          - name: output
          - name: ubuntu-20.04
        run:
          path: build
        outputs:
          - name: image
        params:
          CONTEXT: source
          BUILD_ARGS_FILE: output/build-args-file
          IMAGE_ARG_base_image: ubuntu-20.04/image.tar

    - put: kubernetes-resource-image-1.25
      params:
        image: image/image.tar

- name: build-kubernetes-resource-image-1.26
  public: true
  serial: true
  plan:
  - do:
    - in_parallel:
      - get: kubernetes-resource-release
        trigger: true
      - get: ubuntu-20.04
        params:
          format: oci
        trigger: true
      - get: stable-1.26
        trigger: true

    - task: build-build-args-file
      file: kubernetes-resource-release/ci/tasks/build-build-args-file.yml
      input_mapping:
        version: stable-1.26

    - task: build
      privileged: true
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: concourse/oci-build-task
            tag: latest
        inputs:
          - name: kubernetes-resource-release
            path: source
          - name: output
          - name: ubuntu-20.04
        run:
          path: build
        outputs:
          - name: image
        params:
          CONTEXT: source
          BUILD_ARGS_FILE: output/build-args-file
          IMAGE_ARG_base_image: ubuntu-20.04/image.tar

    - put: kubernetes-resource-image-1.26
      params:
        image: image/image.tar

- name: build-kubernetes-resource-image-1.27
  public: true
  serial: true
  plan:
  - do:
    - in_parallel:
      - get: kubernetes-resource-release
        trigger: true
      - get: ubuntu-20.04
        params:
          format: oci
        trigger: true
      - get: stable-1.27
        trigger: true

    - task: build-build-args-file
      file: kubernetes-resource-release/ci/tasks/build-build-args-file.yml
      input_mapping:
        version: stable-1.27

    - task: build
      privileged: true
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: concourse/oci-build-task
            tag: latest
        inputs:
          - name: kubernetes-resource-release
            path: source
          - name: output
          - name: ubuntu-20.04
        run:
          path: build
        outputs:
          - name: image
        params:
          CONTEXT: source
          BUILD_ARGS_FILE: output/build-args-file
          IMAGE_ARG_base_image: ubuntu-20.04/image.tar

    - put: kubernetes-resource-image-1.27
      params:
        image: image/image.tar

- name: build-kubernetes-resource-image-1.28
  public: true
  serial: true
  plan:
  - do:
    - in_parallel:
      - get: kubernetes-resource-release
        trigger: true
      - get: ubuntu-20.04
        params:
          format: oci
        trigger: true
      - get: stable-1.28
        trigger: true

    - task: build-build-args-file
      file: kubernetes-resource-release/ci/tasks/build-build-args-file.yml
      input_mapping:
        version: stable-1.28

    - task: build
      privileged: true
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: concourse/oci-build-task
            tag: latest
        inputs:
          - name: kubernetes-resource-release
            path: source
          - name: output
          - name: ubuntu-20.04
        run:
          path: build
        outputs:
          - name: image
        params:
          CONTEXT: source
          BUILD_ARGS_FILE: output/build-args-file
          IMAGE_ARG_base_image: ubuntu-20.04/image.tar

    - put: kubernetes-resource-image-1.28
      params:
        image: image/image.tar

- name: build-kubernetes-resource-image-latest
  public: true
  serial: true
  plan:
  - do:
    - in_parallel:
      - get: kubernetes-resource-release
        trigger: true
      - get: ubuntu-20.04
        params:
          format: oci
        trigger: true
      - get: latest
        trigger: true

    - task: build-build-args-file
      file: kubernetes-resource-release/ci/tasks/build-build-args-file.yml
      input_mapping:
        version: latest

    - task: build
      privileged: true
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: concourse/oci-build-task
            tag: latest
        inputs:
          - name: kubernetes-resource-release
            path: source
          - name: output
          - name: ubuntu-20.04
        run:
          path: build
        outputs:
          - name: image
        params:
          CONTEXT: source
          BUILD_ARGS_FILE: output/build-args-file
          IMAGE_ARG_base_image: ubuntu-20.04/image.tar

    - put: kubernetes-resource-image-latest
      params:
        image: image/image.tar

